name: Print Date and Time

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  print-time:
    runs-on: ubuntu-latest
    steps:
      - name: Show current time
        run: |
          echo "Current date and time:"
          date
